name: Deploy Worker
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        env:
          API_KEY: ${{ secrets.API_KEY }}  # 使用 GitHub Secrets 存储的 Proxy API 密钥
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # 使用 GitHub Secrets 存储的 OpenAI API 密钥
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
